export const countries = [
  { code: "+1", flag: "https://flagcdn.com/w40/us.png", name: "United States" },
  { code: "+92", flag: "https://flagcdn.com/w40/pk.png", name: "Pakistan" },
  { code: "+91", flag: "https://flagcdn.com/w40/in.png", name: "India" },
  { code: "+971", flag: "https://flagcdn.com/w40/ae.png", name: "UAE" },
  { code: "+966", flag: "https://flagcdn.com/w40/sa.png", name: "Saudi Arabia" },
  { code: "+44", flag: "https://flagcdn.com/w40/gb.png", name: "United Kingdom" },
  { code: "+93", flag: "https://flagcdn.com/w40/af.png", name: "Afghanistan" },
  { code: "+355", flag: "https://flagcdn.com/w40/al.png", name: "Albania" },
  { code: "+213", flag: "https://flagcdn.com/w40/dz.png", name: "Algeria" },
  { code: "+376", flag: "https://flagcdn.com/w40/ad.png", name: "Andorra" },
  { code: "+244", flag: "https://flagcdn.com/w40/ao.png", name: "Angola" },
  { code: "+1264", flag: "https://flagcdn.com/w40/ai.png", name: "Anguilla" },
  { code: "+1268", flag: "https://flagcdn.com/w40/ag.png", name: "Antigua & Barbuda" },
  { code: "+54", flag: "https://flagcdn.com/w40/ar.png", name: "Argentina" },
  { code: "+374", flag: "https://flagcdn.com/w40/am.png", name: "Armenia" },
  { code: "+297", flag: "https://flagcdn.com/w40/aw.png", name: "Aruba" },
  { code: "+61", flag: "https://flagcdn.com/w40/au.png", name: "Australia" },
  { code: "+43", flag: "https://flagcdn.com/w40/at.png", name: "Austria" },
  { code: "+994", flag: "https://flagcdn.com/w40/az.png", name: "Azerbaijan" },
  { code: "+1242", flag: "https://flagcdn.com/w40/bs.png", name: "Bahamas" },
  { code: "+973", flag: "https://flagcdn.com/w40/bh.png", name: "Bahrain" },
  { code: "+880", flag: "https://flagcdn.com/w40/bd.png", name: "Bangladesh" },
  { code: "+1246", flag: "https://flagcdn.com/w40/bb.png", name: "Barbados" },
  { code: "+375", flag: "https://flagcdn.com/w40/by.png", name: "Belarus" },
  { code: "+32", flag: "https://flagcdn.com/w40/be.png", name: "Belgium" },
  { code: "+501", flag: "https://flagcdn.com/w40/bz.png", name: "Belize" },
  { code: "+229", flag: "https://flagcdn.com/w40/bj.png", name: "Benin" },
  { code: "+1441", flag: "https://flagcdn.com/w40/bm.png", name: "Bermuda" },
  { code: "+975", flag: "https://flagcdn.com/w40/bt.png", name: "Bhutan" },
  { code: "+591", flag: "https://flagcdn.com/w40/bo.png", name: "Bolivia" },
  { code: "+387", flag: "https://flagcdn.com/w40/ba.png", name: "Bosnia" },
  { code: "+267", flag: "https://flagcdn.com/w40/bw.png", name: "Botswana" },
  { code: "+55", flag: "https://flagcdn.com/w40/br.png", name: "Brazil" },
  { code: "+1284", flag: "https://flagcdn.com/w40/vg.png", name: "British Virgin Islands" },
  { code: "+673", flag: "https://flagcdn.com/w40/bn.png", name: "Brunei" },
  { code: "+359", flag: "https://flagcdn.com/w40/bg.png", name: "Bulgaria" },
  { code: "+226", flag: "https://flagcdn.com/w40/bf.png", name: "Burkina Faso" },
  { code: "+257", flag: "https://flagcdn.com/w40/bi.png", name: "Burundi" },
  { code: "+855", flag: "https://flagcdn.com/w40/kh.png", name: "Cambodia" },
  { code: "+237", flag: "https://flagcdn.com/w40/cm.png", name: "Cameroon" },
  { code: "+1", flag: "https://flagcdn.com/w40/ca.png", name: "Canada" },
  { code: "+238", flag: "https://flagcdn.com/w40/cv.png", name: "Cape Verde" },
  { code: "+1345", flag: "https://flagcdn.com/w40/ky.png", name: "Cayman Islands" },
  { code: "+236", flag: "https://flagcdn.com/w40/cf.png", name: "Central African Rep." },
  { code: "+235", flag: "https://flagcdn.com/w40/td.png", name: "Chad" },
  { code: "+56", flag: "https://flagcdn.com/w40/cl.png", name: "Chile" },
  { code: "+86", flag: "https://flagcdn.com/w40/cn.png", name: "China" },
  { code: "+57", flag: "https://flagcdn.com/w40/co.png", name: "Colombia" },
  { code: "+269", flag: "https://flagcdn.com/w40/km.png", name: "Comoros" },
  { code: "+242", flag: "https://flagcdn.com/w40/cg.png", name: "Congo" },
  { code: "+243", flag: "https://flagcdn.com/w40/cd.png", name: "DR Congo" },
  { code: "+682", flag: "https://flagcdn.com/w40/ck.png", name: "Cook Islands" },
  { code: "+506", flag: "https://flagcdn.com/w40/cr.png", name: "Costa Rica" },
  { code: "+385", flag: "https://flagcdn.com/w40/hr.png", name: "Croatia" },
  { code: "+53", flag: "https://flagcdn.com/w40/cu.png", name: "Cuba" },
  { code: "+357", flag: "https://flagcdn.com/w40/cy.png", name: "Cyprus" },
  { code: "+420", flag: "https://flagcdn.com/w40/cz.png", name: "Czechia" },
  { code: "+45", flag: "https://flagcdn.com/w40/dk.png", name: "Denmark" },
  { code: "+253", flag: "https://flagcdn.com/w40/dj.png", name: "Djibouti" },
  { code: "+1767", flag: "https://flagcdn.com/w40/dm.png", name: "Dominica" },
  { code: "+1809", flag: "https://flagcdn.com/w40/do.png", name: "Dominican Republic" },
  { code: "+593", flag: "https://flagcdn.com/w40/ec.png", name: "Ecuador" },
  { code: "+20", flag: "https://flagcdn.com/w40/eg.png", name: "Egypt" },
  { code: "+503", flag: "https://flagcdn.com/w40/sv.png", name: "El Salvador" },
  { code: "+240", flag: "https://flagcdn.com/w40/gq.png", name: "Equatorial Guinea" },
  { code: "+291", flag: "https://flagcdn.com/w40/er.png", name: "Eritrea" },
  { code: "+372", flag: "https://flagcdn.com/w40/ee.png", name: "Estonia" },
  { code: "+268", flag: "https://flagcdn.com/w40/sz.png", name: "Eswatini" },
  { code: "+251", flag: "https://flagcdn.com/w40/et.png", name: "Ethiopia" },
  { code: "+500", flag: "https://flagcdn.com/w40/fk.png", name: "Falkland Islands" },
  { code: "+298", flag: "https://flagcdn.com/w40/fo.png", name: "Faroe Islands" },
  { code: "+679", flag: "https://flagcdn.com/w40/fj.png", name: "Fiji" },
  { code: "+358", flag: "https://flagcdn.com/w40/fi.png", name: "Finland" },
  { code: "+33", flag: "https://flagcdn.com/w40/fr.png", name: "France" },
  { code: "+594", flag: "https://flagcdn.com/w40/gf.png", name: "French Guiana" },
  { code: "+689", flag: "https://flagcdn.com/w40/pf.png", name: "French Polynesia" },
  { code: "+241", flag: "https://flagcdn.com/w40/ga.png", name: "Gabon" },
  { code: "+220", flag: "https://flagcdn.com/w40/gm.png", name: "Gambia" },
  { code: "+995", flag: "https://flagcdn.com/w40/ge.png", name: "Georgia" },
  { code: "+49", flag: "https://flagcdn.com/w40/de.png", name: "Germany" },
  { code: "+233", flag: "https://flagcdn.com/w40/gh.png", name: "Ghana" },
  { code: "+350", flag: "https://flagcdn.com/w40/gi.png", name: "Gibraltar" },
  { code: "+30", flag: "https://flagcdn.com/w40/gr.png", name: "Greece" },
  { code: "+299", flag: "https://flagcdn.com/w40/gl.png", name: "Greenland" },
  { code: "+1473", flag: "https://flagcdn.com/w40/gd.png", name: "Grenada" },
  { code: "+590", flag: "https://flagcdn.com/w40/gp.png", name: "Guadeloupe" },
  { code: "+1671", flag: "https://flagcdn.com/w40/gu.png", name: "Guam" },
  { code: "+502", flag: "https://flagcdn.com/w40/gt.png", name: "Guatemala" },
  { code: "+224", flag: "https://flagcdn.com/w40/gn.png", name: "Guinea" },
  { code: "+245", flag: "https://flagcdn.com/w40/gw.png", name: "Guinea-Bissau" },
  { code: "+592", flag: "https://flagcdn.com/w40/gy.png", name: "Guyana" },
  { code: "+509", flag: "https://flagcdn.com/w40/ht.png", name: "Haiti" },
  { code: "+504", flag: "https://flagcdn.com/w40/hn.png", name: "Honduras" },
  { code: "+852", flag: "https://flagcdn.com/w40/hk.png", name: "Hong Kong" },
  { code: "+36", flag: "https://flagcdn.com/w40/hu.png", name: "Hungary" },
  { code: "+354", flag: "https://flagcdn.com/w40/is.png", name: "Iceland" },
  { code: "+62", flag: "https://flagcdn.com/w40/id.png", name: "Indonesia" },
  { code: "+98", flag: "https://flagcdn.com/w40/ir.png", name: "Iran" },
  { code: "+964", flag: "https://flagcdn.com/w40/iq.png", name: "Iraq" },
  { code: "+353", flag: "https://flagcdn.com/w40/ie.png", name: "Ireland" },
  { code: "+972", flag: "https://flagcdn.com/w40/il.png", name: "Israel" },
  { code: "+39", flag: "https://flagcdn.com/w40/it.png", name: "Italy" },
  { code: "+225", flag: "https://flagcdn.com/w40/ci.png", name: "Ivory Coast" },
  { code: "+1876", flag: "https://flagcdn.com/w40/jm.png", name: "Jamaica" },
  { code: "+81", flag: "https://flagcdn.com/w40/jp.png", name: "Japan" },
  { code: "+962", flag: "https://flagcdn.com/w40/jo.png", name: "Jordan" },
  { code: "+7", flag: "https://flagcdn.com/w40/kz.png", name: "Kazakhstan" },
  { code: "+254", flag: "https://flagcdn.com/w40/ke.png", name: "Kenya" },
  { code: "+686", flag: "https://flagcdn.com/w40/ki.png", name: "Kiribati" },
  { code: "+965", flag: "https://flagcdn.com/w40/kw.png", name: "Kuwait" },
  { code: "+996", flag: "https://flagcdn.com/w40/kg.png", name: "Kyrgyzstan" },
  { code: "+856", flag: "https://flagcdn.com/w40/la.png", name: "Laos" },
  { code: "+371", flag: "https://flagcdn.com/w40/lv.png", name: "Latvia" },
  { code: "+961", flag: "https://flagcdn.com/w40/lb.png", name: "Lebanon" },
  { code: "+266", flag: "https://flagcdn.com/w40/ls.png", name: "Lesotho" },
  { code: "+231", flag: "https://flagcdn.com/w40/lr.png", name: "Liberia" },
  { code: "+218", flag: "https://flagcdn.com/w40/ly.png", name: "Libya" },
  { code: "+423", flag: "https://flagcdn.com/w40/li.png", name: "Liechtenstein" },
  { code: "+370", flag: "https://flagcdn.com/w40/lt.png", name: "Lithuania" },
  { code: "+352", flag: "https://flagcdn.com/w40/lu.png", name: "Luxembourg" },
  { code: "+853", flag: "https://flagcdn.com/w40/mo.png", name: "Macau" },
  { code: "+389", flag: "https://flagcdn.com/w40/mk.png", name: "North Macedonia" },
  { code: "+261", flag: "https://flagcdn.com/w40/mg.png", name: "Madagascar" },
  { code: "+265", flag: "https://flagcdn.com/w40/mw.png", name: "Malawi" },
  { code: "+60", flag: "https://flagcdn.com/w40/my.png", name: "Malaysia" },
  { code: "+960", flag: "https://flagcdn.com/w40/mv.png", name: "Maldives" },
  { code: "+223", flag: "https://flagcdn.com/w40/ml.png", name: "Mali" },
  { code: "+356", flag: "https://flagcdn.com/w40/mt.png", name: "Malta" },
  { code: "+692", flag: "https://flagcdn.com/w40/mh.png", name: "Marshall Islands" },
  { code: "+596", flag: "https://flagcdn.com/w40/mq.png", name: "Martinique" },
  { code: "+222", flag: "https://flagcdn.com/w40/mr.png", name: "Mauritania" },
  { code: "+230", flag: "https://flagcdn.com/w40/mu.png", name: "Mauritius" },
  { code: "+262", flag: "https://flagcdn.com/w40/yt.png", name: "Mayotte" },
  { code: "+52", flag: "https://flagcdn.com/w40/mx.png", name: "Mexico" },
  { code: "+691", flag: "https://flagcdn.com/w40/fm.png", name: "Micronesia" },
  { code: "+373", flag: "https://flagcdn.com/w40/md.png", name: "Moldova" },
  { code: "+377", flag: "https://flagcdn.com/w40/mc.png", name: "Monaco" },
  { code: "+976", flag: "https://flagcdn.com/w40/mn.png", name: "Mongolia" },
  { code: "+382", flag: "https://flagcdn.com/w40/me.png", name: "Montenegro" },
  { code: "+1664", flag: "https://flagcdn.com/w40/ms.png", name: "Montserrat" },
  { code: "+212", flag: "https://flagcdn.com/w40/ma.png", name: "Morocco" },
  { code: "+258", flag: "https://flagcdn.com/w40/mz.png", name: "Mozambique" },
  { code: "+95", flag: "https://flagcdn.com/w40/mm.png", name: "Myanmar" },
  { code: "+264", flag: "https://flagcdn.com/w40/na.png", name: "Namibia" },
  { code: "+674", flag: "https://flagcdn.com/w40/nr.png", name: "Nauru" },
  { code: "+977", flag: "https://flagcdn.com/w40/np.png", name: "Nepal" },
  { code: "+31", flag: "https://flagcdn.com/w40/nl.png", name: "Netherlands" },
  { code: "+687", flag: "https://flagcdn.com/w40/nc.png", name: "New Caledonia" },
  { code: "+64", flag: "https://flagcdn.com/w40/nz.png", name: "New Zealand" },
  { code: "+505", flag: "https://flagcdn.com/w40/ni.png", name: "Nicaragua" },
  { code: "+227", flag: "https://flagcdn.com/w40/ne.png", name: "Niger" },
  { code: "+234", flag: "https://flagcdn.com/w40/ng.png", name: "Nigeria" },
  { code: "+683", flag: "https://flagcdn.com/w40/nu.png", name: "Niue" },
  { code: "+850", flag: "https://flagcdn.com/w40/kp.png", name: "North Korea" },
  { code: "+1670", flag: "https://flagcdn.com/w40/mp.png", name: "Northern Mariana Islands" },
  { code: "+47", flag: "https://flagcdn.com/w40/no.png", name: "Norway" },
  { code: "+968", flag: "https://flagcdn.com/w40/om.png", name: "Oman" },
  { code: "+680", flag: "https://flagcdn.com/w40/pw.png", name: "Palau" },
  { code: "+970", flag: "https://flagcdn.com/w40/ps.png", name: "Palestine" },
  { code: "+507", flag: "https://flagcdn.com/w40/pa.png", name: "Panama" },
  { code: "+675", flag: "https://flagcdn.com/w40/pg.png", name: "Papua New Guinea" },
  { code: "+595", flag: "https://flagcdn.com/w40/py.png", name: "Paraguay" },
  { code: "+51", flag: "https://flagcdn.com/w40/pe.png", name: "Peru" },
  { code: "+63", flag: "https://flagcdn.com/w40/ph.png", name: "Philippines" },
  { code: "+48", flag: "https://flagcdn.com/w40/pl.png", name: "Poland" },
  { code: "+351", flag: "https://flagcdn.com/w40/pt.png", name: "Portugal" },
  { code: "+1787", flag: "https://flagcdn.com/w40/pr.png", name: "Puerto Rico" },
  { code: "+974", flag: "https://flagcdn.com/w40/qa.png", name: "Qatar" },
  { code: "+262", flag: "https://flagcdn.com/w40/re.png", name: "Reunion" },
  { code: "+40", flag: "https://flagcdn.com/w40/ro.png", name: "Romania" },
  { code: "+7", flag: "https://flagcdn.com/w40/ru.png", name: "Russia" },
  { code: "+250", flag: "https://flagcdn.com/w40/rw.png", name: "Rwanda" },
  { code: "+290", flag: "https://flagcdn.com/w40/sh.png", name: "Saint Helena" },
  { code: "+1869", flag: "https://flagcdn.com/w40/kn.png", name: "Saint Kitts & Nevis" },
  { code: "+1758", flag: "https://flagcdn.com/w40/lc.png", name: "Saint Lucia" },
  { code: "+508", flag: "https://flagcdn.com/w40/pm.png", name: "St. Pierre & Miquelon" },
  { code: "+1784", flag: "https://flagcdn.com/w40/vc.png", name: "Saint Vincent" },
  { code: "+685", flag: "https://flagcdn.com/w40/ws.png", name: "Samoa" },
  { code: "+378", flag: "https://flagcdn.com/w40/sm.png", name: "San Marino" },
  { code: "+239", flag: "https://flagcdn.com/w40/st.png", name: "Sao Tome" },
  { code: "+221", flag: "https://flagcdn.com/w40/sn.png", name: "Senegal" },
  { code: "+381", flag: "https://flagcdn.com/w40/rs.png", name: "Serbia" },
  { code: "+248", flag: "https://flagcdn.com/w40/sc.png", name: "Seychelles" },
  { code: "+232", flag: "https://flagcdn.com/w40/sl.png", name: "Sierra Leone" },
  { code: "+65", flag: "https://flagcdn.com/w40/sg.png", name: "Singapore" },
  { code: "+421", flag: "https://flagcdn.com/w40/sk.png", name: "Slovakia" },
  { code: "+386", flag: "https://flagcdn.com/w40/si.png", name: "Slovenia" },
  { code: "+677", flag: "https://flagcdn.com/w40/sb.png", name: "Solomon Islands" },
  { code: "+252", flag: "https://flagcdn.com/w40/so.png", name: "Somalia" },
  { code: "+27", flag: "https://flagcdn.com/w40/za.png", name: "South Africa" },
  { code: "+82", flag: "https://flagcdn.com/w40/kr.png", name: "South Korea" },
  { code: "+211", flag: "https://flagcdn.com/w40/ss.png", name: "South Sudan" },
  { code: "+34", flag: "https://flagcdn.com/w40/es.png", name: "Spain" },
  { code: "+94", flag: "https://flagcdn.com/w40/lk.png", name: "Sri Lanka" },
  { code: "+249", flag: "https://flagcdn.com/w40/sd.png", name: "Sudan" },
  { code: "+597", flag: "https://flagcdn.com/w40/sr.png", name: "Suriname" },
  { code: "+46", flag: "https://flagcdn.com/w40/se.png", name: "Sweden" },
  { code: "+41", flag: "https://flagcdn.com/w40/ch.png", name: "Switzerland" },
  { code: "+963", flag: "https://flagcdn.com/w40/sy.png", name: "Syria" },
  { code: "+886", flag: "https://flagcdn.com/w40/tw.png", name: "Taiwan" },
  { code: "+992", flag: "https://flagcdn.com/w40/tj.png", name: "Tajikistan" },
  { code: "+255", flag: "https://flagcdn.com/w40/tz.png", name: "Tanzania" },
  { code: "+66", flag: "https://flagcdn.com/w40/th.png", name: "Thailand" },
  { code: "+228", flag: "https://flagcdn.com/w40/tg.png", name: "Togo" },
  { code: "+690", flag: "https://flagcdn.com/w40/tk.png", name: "Tokelau" },
  { code: "+676", flag: "https://flagcdn.com/w40/to.png", name: "Tonga" },
  { code: "+1868", flag: "https://flagcdn.com/w40/tt.png", name: "Trinidad" },
  { code: "+216", flag: "https://flagcdn.com/w40/tn.png", name: "Tunisia" },
  { code: "+90", flag: "https://flagcdn.com/w40/tr.png", name: "Turkey" },
  { code: "+993", flag: "https://flagcdn.com/w40/tm.png", name: "Turkmenistan" },
  { code: "+1649", flag: "https://flagcdn.com/w40/tc.png", name: "Turks & Caicos" },
  { code: "+688", flag: "https://flagcdn.com/w40/tv.png", name: "Tuvalu" },
  { code: "+256", flag: "https://flagcdn.com/w40/ug.png", name: "Uganda" },
  { code: "+380", flag: "https://flagcdn.com/w40/ua.png", name: "Ukraine" },
  { code: "+598", flag: "https://flagcdn.com/w40/uy.png", name: "Uruguay" },
  { code: "+998", flag: "https://flagcdn.com/w40/uz.png", name: "Uzbekistan" },
  { code: "+678", flag: "https://flagcdn.com/w40/vu.png", name: "Vanuatu" },
  { code: "+39", flag: "https://flagcdn.com/w40/va.png", name: "Vatican City" },
  { code: "+58", flag: "https://flagcdn.com/w40/ve.png", name: "Venezuela" },
  { code: "+84", flag: "https://flagcdn.com/w40/vn.png", name: "Vietnam" },
  { code: "+1340", flag: "https://flagcdn.com/w40/vi.png", name: "US Virgin Islands" },
  { code: "+681", flag: "https://flagcdn.com/w40/wf.png", name: "Wallis & Futuna" },
  { code: "+967", flag: "https://flagcdn.com/w40/ye.png", name: "Yemen" },
  { code: "+260", flag: "https://flagcdn.com/w40/zm.png", name: "Zambia" },
  { code: "+263", flag: "https://flagcdn.com/w40/zw.png", name: "Zimbabwe" }
]
